version: "3"
services:
  nodeScore:
    container_name: webScore
    image: node:alpine
    working_dir: /usr/app
    volumes:
      - ../web/:/usr/app/
    ports:
      - 3003:3003
    command: sh -c "npm install && npm run start"
    networks:
      consumidor_net:
        ipv4_address: 172.25.0.10
  mongodb:
    image: mongo:latest
    container_name: dbScore
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=dbScore
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=myP4ssw0rd
    volumes:
      - ../database/mongodb/data/:/data/db
      - ../database/config/mongo.js:/docker-entrypoint-initdb.d/mongo.js
    networks:
      consumidor_net:
        ipv4_address: 172.25.0.11

networks:
  consumidor_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
